name: "Hello World"
description: "Greet someone and record the time"
inputs:
  python-root-list:
    description: "A list with all paths to be test"
    required: false
    default: "."
  use-pylint: # id of input
    description: "User Pylint"
    required: false
    default: true
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.python-root-list }}
    - ${{ inputs.use-pylint }}
