name: "Hello World"
description: "Greet someone and record the time"
inputs:
  code-root:
    description: "Code Root"
    required: false
    default: "."
  use-pylint: # id of input
    description: "User Pylint"
    required: false
    default: true
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.code-root }}
    - ${{ inputs.use-pylint }}
