name: "Hello World"
description: "Greet someone and record the time"
inputs:
  python-root-list:
    description: "A list with all paths to be test"
    required: false
    default: "."
  use-pylint:
    description: "User Pylint"
    required: false
    default: true
  use-pycodestyle:
    description: "User pycodestyle"
    required: false
    default: true
  use-flake8:
    description: "User Flake8"
    required: false
    default: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.python-root-list }}
    - ${{ inputs.use-pylint }}
    - ${{ inputs.use-pycodestyle }}
    - ${{ inputs.use-flake8 }}
