name: all-lints

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: 654wak654/python-lint@master
        with:
          python-root-list: "tests"
